Document: obed
Title: Debian obed Manual
Author: <insert document author here>
Abstract: This manual describes what obed is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/obed/obed.sgml.gz

Format: postscript
Files: /usr/share/doc/obed/obed.ps.gz

Format: text
Files: /usr/share/doc/obed/obed.text.gz

Format: HTML
Index: /usr/share/doc/obed/html/index.html
Files: /usr/share/doc/obed/html/*.html
