/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "obed.pb-c.h"
void   obed__input_opts__init
                     (Obed__InputOpts         *message)
{
  static Obed__InputOpts init_value = OBED__INPUT_OPTS__INIT;
  *message = init_value;
}
size_t obed__input_opts__get_packed_size
                     (const Obed__InputOpts *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__input_opts__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obed__input_opts__pack
                     (const Obed__InputOpts *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__input_opts__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obed__input_opts__pack_to_buffer
                     (const Obed__InputOpts *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__input_opts__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Obed__InputOpts *
       obed__input_opts__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Obed__InputOpts *)
     protobuf_c_message_unpack (&obed__input_opts__descriptor,
                                allocator, len, data);
}
void   obed__input_opts__free_unpacked
                     (Obed__InputOpts *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__input_opts__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   obed__video_opts__init
                     (Obed__VideoOpts         *message)
{
  static Obed__VideoOpts init_value = OBED__VIDEO_OPTS__INIT;
  *message = init_value;
}
size_t obed__video_opts__get_packed_size
                     (const Obed__VideoOpts *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__video_opts__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obed__video_opts__pack
                     (const Obed__VideoOpts *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__video_opts__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obed__video_opts__pack_to_buffer
                     (const Obed__VideoOpts *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__video_opts__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Obed__VideoOpts *
       obed__video_opts__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Obed__VideoOpts *)
     protobuf_c_message_unpack (&obed__video_opts__descriptor,
                                allocator, len, data);
}
void   obed__video_opts__free_unpacked
                     (Obed__VideoOpts *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__video_opts__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   obed__audio_opts__init
                     (Obed__AudioOpts         *message)
{
  static Obed__AudioOpts init_value = OBED__AUDIO_OPTS__INIT;
  *message = init_value;
}
size_t obed__audio_opts__get_packed_size
                     (const Obed__AudioOpts *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__audio_opts__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obed__audio_opts__pack
                     (const Obed__AudioOpts *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__audio_opts__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obed__audio_opts__pack_to_buffer
                     (const Obed__AudioOpts *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__audio_opts__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Obed__AudioOpts *
       obed__audio_opts__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Obed__AudioOpts *)
     protobuf_c_message_unpack (&obed__audio_opts__descriptor,
                                allocator, len, data);
}
void   obed__audio_opts__free_unpacked
                     (Obed__AudioOpts *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__audio_opts__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   obed__ancillary_opts__init
                     (Obed__AncillaryOpts         *message)
{
  static Obed__AncillaryOpts init_value = OBED__ANCILLARY_OPTS__INIT;
  *message = init_value;
}
size_t obed__ancillary_opts__get_packed_size
                     (const Obed__AncillaryOpts *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__ancillary_opts__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obed__ancillary_opts__pack
                     (const Obed__AncillaryOpts *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__ancillary_opts__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obed__ancillary_opts__pack_to_buffer
                     (const Obed__AncillaryOpts *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__ancillary_opts__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Obed__AncillaryOpts *
       obed__ancillary_opts__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Obed__AncillaryOpts *)
     protobuf_c_message_unpack (&obed__ancillary_opts__descriptor,
                                allocator, len, data);
}
void   obed__ancillary_opts__free_unpacked
                     (Obed__AncillaryOpts *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__ancillary_opts__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   obed__mux_opts__init
                     (Obed__MuxOpts         *message)
{
  static Obed__MuxOpts init_value = OBED__MUX_OPTS__INIT;
  *message = init_value;
}
size_t obed__mux_opts__get_packed_size
                     (const Obed__MuxOpts *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__mux_opts__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obed__mux_opts__pack
                     (const Obed__MuxOpts *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__mux_opts__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obed__mux_opts__pack_to_buffer
                     (const Obed__MuxOpts *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__mux_opts__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Obed__MuxOpts *
       obed__mux_opts__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Obed__MuxOpts *)
     protobuf_c_message_unpack (&obed__mux_opts__descriptor,
                                allocator, len, data);
}
void   obed__mux_opts__free_unpacked
                     (Obed__MuxOpts *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__mux_opts__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   obed__output_opts__init
                     (Obed__OutputOpts         *message)
{
  static Obed__OutputOpts init_value = OBED__OUTPUT_OPTS__INIT;
  *message = init_value;
}
size_t obed__output_opts__get_packed_size
                     (const Obed__OutputOpts *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__output_opts__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obed__output_opts__pack
                     (const Obed__OutputOpts *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__output_opts__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obed__output_opts__pack_to_buffer
                     (const Obed__OutputOpts *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__output_opts__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Obed__OutputOpts *
       obed__output_opts__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Obed__OutputOpts *)
     protobuf_c_message_unpack (&obed__output_opts__descriptor,
                                allocator, len, data);
}
void   obed__output_opts__free_unpacked
                     (Obed__OutputOpts *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__output_opts__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   obed__encoder_control__init
                     (Obed__EncoderControl         *message)
{
  static Obed__EncoderControl init_value = OBED__ENCODER_CONTROL__INIT;
  *message = init_value;
}
size_t obed__encoder_control__get_packed_size
                     (const Obed__EncoderControl *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__encoder_control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obed__encoder_control__pack
                     (const Obed__EncoderControl *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__encoder_control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obed__encoder_control__pack_to_buffer
                     (const Obed__EncoderControl *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__encoder_control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Obed__EncoderControl *
       obed__encoder_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Obed__EncoderControl *)
     protobuf_c_message_unpack (&obed__encoder_control__descriptor,
                                allocator, len, data);
}
void   obed__encoder_control__free_unpacked
                     (Obed__EncoderControl *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__encoder_control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   obed__encoder_response__init
                     (Obed__EncoderResponse         *message)
{
  static Obed__EncoderResponse init_value = OBED__ENCODER_RESPONSE__INIT;
  *message = init_value;
}
size_t obed__encoder_response__get_packed_size
                     (const Obed__EncoderResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__encoder_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obed__encoder_response__pack
                     (const Obed__EncoderResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__encoder_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obed__encoder_response__pack_to_buffer
                     (const Obed__EncoderResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__encoder_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Obed__EncoderResponse *
       obed__encoder_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Obed__EncoderResponse *)
     protobuf_c_message_unpack (&obed__encoder_response__descriptor,
                                allocator, len, data);
}
void   obed__encoder_response__free_unpacked
                     (Obed__EncoderResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &obed__encoder_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor obed__input_opts__field_descriptors[3] =
{
  {
    "input_device",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__InputOpts, input_device),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "card_idx",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__InputOpts, card_idx),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "video_format",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__InputOpts, video_format),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obed__input_opts__field_indices_by_name[] = {
  1,   /* field[1] = card_idx */
  0,   /* field[0] = input_device */
  2,   /* field[2] = video_format */
};
static const ProtobufCIntRange obed__input_opts__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor obed__input_opts__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "obed.InputOpts",
  "InputOpts",
  "Obed__InputOpts",
  "obed",
  sizeof(Obed__InputOpts),
  3,
  obed__input_opts__field_descriptors,
  obed__input_opts__field_indices_by_name,
  1,  obed__input_opts__number_ranges,
  (ProtobufCMessageInit) obed__input_opts__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor obed__video_opts__field_descriptors[14] =
{
  {
    "profile",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, profile),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitrate",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, bitrate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vbv_bufsize",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, vbv_bufsize),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keyint",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, keyint),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bframes",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, bframes),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_refs",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, max_refs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lookahead",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, lookahead),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quality_metric",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, quality_metric),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, width),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aspect_ratio",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, aspect_ratio),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "afd_passthrough",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, afd_passthrough),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wss_to_afd",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, wss_to_afd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_packing",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__VideoOpts, frame_packing),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obed__video_opts__field_indices_by_name[] = {
  11,   /* field[11] = afd_passthrough */
  10,   /* field[10] = aspect_ratio */
  4,   /* field[4] = bframes */
  1,   /* field[1] = bitrate */
  13,   /* field[13] = frame_packing */
  3,   /* field[3] = keyint */
  6,   /* field[6] = lookahead */
  5,   /* field[5] = max_refs */
  8,   /* field[8] = pid */
  0,   /* field[0] = profile */
  7,   /* field[7] = quality_metric */
  2,   /* field[2] = vbv_bufsize */
  9,   /* field[9] = width */
  12,   /* field[12] = wss_to_afd */
};
static const ProtobufCIntRange obed__video_opts__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor obed__video_opts__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "obed.VideoOpts",
  "VideoOpts",
  "Obed__VideoOpts",
  "obed",
  sizeof(Obed__VideoOpts),
  14,
  obed__video_opts__field_descriptors,
  obed__video_opts__field_indices_by_name,
  1,  obed__video_opts__number_ranges,
  (ProtobufCMessageInit) obed__video_opts__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor obed__audio_opts__field_descriptors[11] =
{
  {
    "format",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, format),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel_map",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, channel_map),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitrate",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, bitrate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sdi_pair",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, sdi_pair),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aac_encap",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, aac_encap),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mp2_mode",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, mp2_mode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mono_channel",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, mono_channel),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reference_level",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, reference_level),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lang_code",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, lang_code),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AudioOpts, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obed__audio_opts__field_indices_by_name[] = {
  4,   /* field[4] = aac_encap */
  2,   /* field[2] = bitrate */
  1,   /* field[1] = channel_map */
  0,   /* field[0] = format */
  9,   /* field[9] = lang_code */
  6,   /* field[6] = mono_channel */
  5,   /* field[5] = mp2_mode */
  8,   /* field[8] = pid */
  7,   /* field[7] = reference_level */
  3,   /* field[3] = sdi_pair */
  10,   /* field[10] = type */
};
static const ProtobufCIntRange obed__audio_opts__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor obed__audio_opts__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "obed.AudioOpts",
  "AudioOpts",
  "Obed__AudioOpts",
  "obed",
  sizeof(Obed__AudioOpts),
  11,
  obed__audio_opts__field_descriptors,
  obed__audio_opts__field_indices_by_name,
  1,  obed__audio_opts__number_ranges,
  (ProtobufCMessageInit) obed__audio_opts__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor obed__ancillary_opts__field_descriptors[14] =
{
  {
    "cea_608",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, cea_608),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cea_708",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, cea_708),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ttx_type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, ttx_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ttx_lang_code",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, ttx_lang_code),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ttx_mag_number",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, ttx_mag_number),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ttx_page_number",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, ttx_page_number),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dvb_ttx_enabled",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, dvb_ttx_enabled),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dvb_ttx_pid",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, dvb_ttx_pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dvb_vbi_enabled",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, dvb_vbi_enabled),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dvb_vbi_pid",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, dvb_vbi_pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dvb_vbi_ttx",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, dvb_vbi_ttx),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dvb_vbi_inverted_ttx",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, dvb_vbi_inverted_ttx),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dvb_vbi_vps",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, dvb_vbi_vps),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dvb_vbi_wss",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__AncillaryOpts, dvb_vbi_wss),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obed__ancillary_opts__field_indices_by_name[] = {
  0,   /* field[0] = cea_608 */
  1,   /* field[1] = cea_708 */
  6,   /* field[6] = dvb_ttx_enabled */
  7,   /* field[7] = dvb_ttx_pid */
  8,   /* field[8] = dvb_vbi_enabled */
  11,   /* field[11] = dvb_vbi_inverted_ttx */
  9,   /* field[9] = dvb_vbi_pid */
  10,   /* field[10] = dvb_vbi_ttx */
  12,   /* field[12] = dvb_vbi_vps */
  13,   /* field[13] = dvb_vbi_wss */
  3,   /* field[3] = ttx_lang_code */
  4,   /* field[4] = ttx_mag_number */
  5,   /* field[5] = ttx_page_number */
  2,   /* field[2] = ttx_type */
};
static const ProtobufCIntRange obed__ancillary_opts__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor obed__ancillary_opts__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "obed.AncillaryOpts",
  "AncillaryOpts",
  "Obed__AncillaryOpts",
  "obed",
  sizeof(Obed__AncillaryOpts),
  14,
  obed__ancillary_opts__field_descriptors,
  obed__ancillary_opts__field_indices_by_name,
  1,  obed__ancillary_opts__number_ranges,
  (ProtobufCMessageInit) obed__ancillary_opts__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor obed__mux_opts__field_descriptors[11] =
{
  {
    "muxrate",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, muxrate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ts_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, ts_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "null_packets",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, null_packets),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pcr_pid",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, pcr_pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pmt_pid",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, pmt_pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "program_num",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, program_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ts_id",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, ts_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pat_period",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, pat_period),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pcr_period",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, pcr_period),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "service_name",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, service_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "provider_name",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__MuxOpts, provider_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obed__mux_opts__field_indices_by_name[] = {
  0,   /* field[0] = muxrate */
  2,   /* field[2] = null_packets */
  7,   /* field[7] = pat_period */
  8,   /* field[8] = pcr_period */
  3,   /* field[3] = pcr_pid */
  4,   /* field[4] = pmt_pid */
  5,   /* field[5] = program_num */
  10,   /* field[10] = provider_name */
  9,   /* field[9] = service_name */
  6,   /* field[6] = ts_id */
  1,   /* field[1] = ts_type */
};
static const ProtobufCIntRange obed__mux_opts__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor obed__mux_opts__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "obed.MuxOpts",
  "MuxOpts",
  "Obed__MuxOpts",
  "obed",
  sizeof(Obed__MuxOpts),
  11,
  obed__mux_opts__field_descriptors,
  obed__mux_opts__field_indices_by_name,
  1,  obed__mux_opts__number_ranges,
  (ProtobufCMessageInit) obed__mux_opts__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor obed__output_opts__field_descriptors[5] =
{
  {
    "method",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__OutputOpts, method),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_address",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__OutputOpts, ip_address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__OutputOpts, port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ttl",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__OutputOpts, ttl),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "miface",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__OutputOpts, miface),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obed__output_opts__field_indices_by_name[] = {
  1,   /* field[1] = ip_address */
  0,   /* field[0] = method */
  4,   /* field[4] = miface */
  2,   /* field[2] = port */
  3,   /* field[3] = ttl */
};
static const ProtobufCIntRange obed__output_opts__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor obed__output_opts__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "obed.OutputOpts",
  "OutputOpts",
  "Obed__OutputOpts",
  "obed",
  sizeof(Obed__OutputOpts),
  5,
  obed__output_opts__field_descriptors,
  obed__output_opts__field_indices_by_name,
  1,  obed__output_opts__number_ranges,
  (ProtobufCMessageInit) obed__output_opts__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor obed__encoder_control__field_descriptors[8] =
{
  {
    "encoder_action",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__EncoderControl, encoder_action),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "control_version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__EncoderControl, control_version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_opts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__EncoderControl, input_opts),
    &obed__input_opts__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "video_opts",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__EncoderControl, video_opts),
    &obed__video_opts__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio_opts",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Obed__EncoderControl, n_audio_opts),
    PROTOBUF_C_OFFSETOF(Obed__EncoderControl, audio_opts),
    &obed__audio_opts__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ancillary_opts",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__EncoderControl, ancillary_opts),
    &obed__ancillary_opts__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mux_opts",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__EncoderControl, mux_opts),
    &obed__mux_opts__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_opts",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Obed__EncoderControl, n_output_opts),
    PROTOBUF_C_OFFSETOF(Obed__EncoderControl, output_opts),
    &obed__output_opts__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obed__encoder_control__field_indices_by_name[] = {
  5,   /* field[5] = ancillary_opts */
  4,   /* field[4] = audio_opts */
  1,   /* field[1] = control_version */
  0,   /* field[0] = encoder_action */
  2,   /* field[2] = input_opts */
  6,   /* field[6] = mux_opts */
  7,   /* field[7] = output_opts */
  3,   /* field[3] = video_opts */
};
static const ProtobufCIntRange obed__encoder_control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor obed__encoder_control__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "obed.EncoderControl",
  "EncoderControl",
  "Obed__EncoderControl",
  "obed",
  sizeof(Obed__EncoderControl),
  8,
  obed__encoder_control__field_descriptors,
  obed__encoder_control__field_indices_by_name,
  1,  obed__encoder_control__number_ranges,
  (ProtobufCMessageInit) obed__encoder_control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor obed__encoder_response__field_descriptors[1] =
{
  {
    "encoder_response",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Obed__EncoderResponse, encoder_response),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obed__encoder_response__field_indices_by_name[] = {
  0,   /* field[0] = encoder_response */
};
static const ProtobufCIntRange obed__encoder_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor obed__encoder_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "obed.EncoderResponse",
  "EncoderResponse",
  "Obed__EncoderResponse",
  "obed",
  sizeof(Obed__EncoderResponse),
  1,
  obed__encoder_response__field_descriptors,
  obed__encoder_response__field_indices_by_name,
  1,  obed__encoder_response__number_ranges,
  (ProtobufCMessageInit) obed__encoder_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor obed__encoder_config__method_descriptors[1] =
{
  { "EncoderConfig", &obed__encoder_control__descriptor, &obed__encoder_response__descriptor },
};
const unsigned obed__encoder_config__method_indices_by_name[] = {
  0         /* EncoderConfig */
};
const ProtobufCServiceDescriptor obed__encoder_config__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "obed.EncoderConfig",
  "EncoderConfig",
  "Obed__EncoderConfig",
  "obed",
  1,
  obed__encoder_config__method_descriptors,
  obed__encoder_config__method_indices_by_name
};
void obed__encoder_config__encoder_config(ProtobufCService *service,
                                          const Obed__EncoderControl *input,
                                          Obed__EncoderResponse_Closure closure,
                                          void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &obed__encoder_config__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void obed__encoder_config__init (Obed__EncoderConfig_Service *service,
                                 Obed__EncoderConfig_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &obed__encoder_config__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
